package io.gongarce.ud2_mvc.presentation.view.person;

import io.gongarce.ud2_mvc.presentation.controller.DetailController;
import io.gongarce.ud2_mvc.presentation.controller.SearchListController2;
import io.gongarce.ud2_mvc.presentation.controller.person.MailListControllerAction;
import io.gongarce.ud2_mvc.presentation.controller.person.PersonUpdateControllerAction;
import io.gongarce.ud2_mvc.presentation.model.ListTableModel;
import io.gongarce.ud2_mvc.presentation.model.MasterModel;
import io.gongarce.ud2_mvc.presentation.model.SinglePropertyModel;
import io.gongarce.ud2_mvc.presentation.model.document.InmutableDocument;
import io.gongarce.ud2_mvc.presentation.model.document.ModelDocument;
import io.gongarce.ud2_mvc.presentation.model.person.TableMail;
import io.gongarce.ud2_mvc.presentation.model.person.TablePerson;
import io.gongarce.ud2_mvc.presentation.view.DisabledGlassPane;
import io.gongarce.ud2_mvc.presentation.view.PluggableView;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Gonzalo
 */
public class PersonDetailPanel extends javax.swing.JPanel implements PluggableView<JPanel> {

    SearchListController2<TableMail> tableController;

    /**
     * Creates new form PersonDetailPanel
     *
     * @param masterModel
     * @param person
     */
    public PersonDetailPanel(MasterModel<TablePerson> masterModel, TablePerson person) {
        initComponents();

        ModelDocument<TablePerson> modelDocument = new ModelDocument<>(person.from());

        txtNif.setDocument(modelDocument.newDocument(TablePerson::setNif));
        txtName.setDocument(modelDocument.newDocument(TablePerson::setName));
        txtPlace.setDocument(modelDocument.newDocument(TablePerson::setPlace));

        txtNif.setText(person.getNif());
        txtName.setText(person.getName());
        txtPlace.setText(person.getPlace());

        SinglePropertyModel<Boolean> loadingModel = SinglePropertyModel.<Boolean>builder()
                .property(Boolean.FALSE)
                .listener(this::setLoadingStatus)
                .build();

        DetailController<TablePerson> controller = new DetailController<>(
                new PersonUpdateControllerAction(),
                masterModel,
                person,
                modelDocument,
                loadingModel
        );
        btnSave.addActionListener(controller);

        List<ListTableModel.TableColum<TableMail, ?>> columns = new ArrayList<>(3);
        columns.add(new ListTableModel.TableColum<>("ID", Long.class, TableMail::getId, null, false));
        columns.add(new ListTableModel.TableColum<>("Address", String.class, TableMail::getAddress, TableMail::setAddress));
        ListTableModel<TableMail> tableModel = new ListTableModel<>(columns);
        tableMails.setModel(tableModel);

        tableController = new SearchListController2<>(
                new MailListControllerAction(),
                new InmutableDocument(person.getNif()),
                tableModel,
                loadingModel
        );
    }

    private void setLoadingStatus(boolean loadingStatus) {
        if (loadingStatus) {
            DisabledGlassPane.show(this, "Loading...");
        } else {
            DisabledGlassPane.hide(this);
        }
    }

    @Override
    public JPanel getView() {
        return this;
    }

    @Override
    public void attach() {
        tableController.actionPerformed(new ActionEvent(this, 0, "Load"));
    }

    @Override
    public void dettach() {
        tableController = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNif = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPlace = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMails = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWeights = new double[] {0.0, 0.3, 0.0, 0.7};
        jPanel1Layout.rowWeights = new double[] {0.0, 0.0, 1.0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("NIF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(txtNif, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(txtName, gridBagConstraints);

        jLabel3.setText("Lugar Nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(txtPlace, gridBagConstraints);

        tableMails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMails);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        btnSave.setText("Save");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(btnSave, gridBagConstraints);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMails;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtPlace;
    // End of variables declaration//GEN-END:variables

}
