package io.gongarce.ud2_mvc.presentation.view.person;

import io.gongarce.ud2_mvc.presentation.controller.person.PersonListController;
import io.gongarce.ud2_mvc.presentation.controller.person.PersonListControllerAction;
import io.gongarce.ud2_mvc.presentation.controller.SearchListController2;
import io.gongarce.ud2_mvc.presentation.controller.click.DoubleClickController;
import io.gongarce.ud2_mvc.presentation.model.ListTableModel;
import io.gongarce.ud2_mvc.presentation.model.SinglePropertyModel;
import io.gongarce.ud2_mvc.presentation.model.person.TablePerson;
import io.gongarce.ud2_mvc.presentation.view.AppModalDialog;
import io.gongarce.ud2_mvc.presentation.view.DisabledGlassPane;
import java.util.ArrayList;
import java.util.EventObject;
import java.util.List;
import static java.util.Objects.nonNull;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Gonzalo
 */
public class PersonListPanel extends javax.swing.JPanel {

    ListTableModel<TablePerson> tableModel;

    public PersonListPanel() {
        initComponents();

        // This view is the only component that knows we are going to work with Persons
        // so is the responsible of creating the particular model
        List<ListTableModel.TableColum<TablePerson, ?>> columns = new ArrayList<>(3);
        columns.add(new ListTableModel.TableColum<>("NIF", String.class, TablePerson::getNif, null, false));
        columns.add(new ListTableModel.TableColum<>("Nombre", String.class, TablePerson::getName, null, false));
        columns.add(new ListTableModel.TableColum<>("Ciudad", String.class, TablePerson::getPlace, null, false));
        tableModel = new ListTableModel<>(columns);
        tablePersons.setModel(tableModel);

        // Create a loading status model to be notified and update the UI
        SinglePropertyModel<Boolean> loadingModel = SinglePropertyModel.<Boolean>builder()
                .property(false)
                .listener(this::loadingStatusChanged)
                .build();

        // We will test to different controller implementations
        // Button: First one inherits from base SearchController and adds the use case call 
        PersonListController controller = new PersonListController(txtSearch.getDocument(), tableModel, loadingModel);
        btnSearch.addActionListener(controller);

        // Text field "Enter ↵": Second one use SearchController and pass an implementation of the search on creation
        SearchListController2 controller2 = new SearchListController2<>(
                PersonListControllerAction.create(),
                txtSearch.getDocument(), tableModel, loadingModel);
        txtSearch.addActionListener(controller2);

        tablePersons.addMouseListener(DoubleClickController.execute(this::detailVisibilityChanged));
    }

    private void detailVisibilityChanged(EventObject e) {
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        TablePerson person = (TablePerson) ((ListTableModel) tablePersons.getModel()).getRowValue(tablePersons.convertRowIndexToModel(tablePersons.getSelectedRow()));
        JDialog dialog = new AppModalDialog(frame, new PersonDetailPanel(tableModel, person));
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
    }

    private void loadingStatusChanged(boolean loadingStatus) {
        if (loadingStatus) {
            DisabledGlassPane.show(this, "Searching...");
        } else {
            DisabledGlassPane.hide(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePersons = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {270, 30};
        jPanel1Layout.columnWeights = new double[] {0.9, 0.1};
        jPanel1Layout.rowWeights = new double[] {0.0, 1.0};
        jPanel1.setLayout(jPanel1Layout);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(txtSearch, gridBagConstraints);

        btnSearch.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(btnSearch, gridBagConstraints);

        tablePersons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablePersons);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jScrollPane2, gridBagConstraints);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablePersons;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
