package io.gongarce.ud2_mvc.presentation.view;

import java.util.Objects;

/**
 *
 * @author Gonzalo
 */
public final class AppModalDialog extends javax.swing.JDialog {

    private PluggableView view;

    public AppModalDialog(java.awt.Frame parent, PluggableView view) {
        super(parent, true);
        //initComponents();
        this.view = view;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(view.getView());
        pack();
    }

    @Override
    public void dispose() {
        super.dispose();
        if (Objects.nonNull(view)) {
            view.dettach();
            this.view = null;
        }
    }

    @Override
    public void pack() {
        super.pack();
        view.attach();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
